use_frameworks!

platform :ios, '10.0'

target 'TeneasyChatSDKUI_iOS_Example' do
  #pod 'TeneasyChatSDKUI_iOS', :git => 'https://github.com/tianxuefeng/TeneasyChatSDKUI_iOS.git'
  pod 'TeneasyChatSDKUI_iOS', :path => '../'
  pod 'SnapKit', '~> 5.0.1'
  pod 'TeneasyChatSDK_iOS', :git => 'https://github.com/tianxuefeng/TeneasyChatSDK_iOS.git'
  target 'TeneasyChatSDKUI_iOS_Tests' do
    inherit! :search_paths

    
  end
end
